<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="Hexa.NET.ImGui" Version="2.2.9" />
    <PackageVersion Include="ktsu.CaseConverter" Version="1.3.35" />
    <PackageVersion Include="ktsu.CredentialCache" Version="1.3.31" />
    <PackageVersion Include="ktsu.ImGui.Popups" Version="3.16.2" />
    <PackageVersion Include="ktsu.Semantics.Strings" Version="3.2.1" />
    <PackageVersion Include="Polyfill" Version="11.2.0" />
  </ItemGroup>
</Project>
